[package]
name = "adabt-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
adabt-core.workspace = true
adabt-telemetry.workspace = true
lz4_flex = { version = "0.14.0", default-features = false, features = ["safe-encode", "safe-decode", "checked-decode", "std"] }

[dev-dependencies]
adabt-testkit.workspace = true
