[package]
name = "adabt-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
adabt-core.workspace = true
adabt-ir.workspace = true
adabt-index.workspace = true
adabt-exec.workspace = true
adabt-storage.workspace = true
adabt-telemetry.workspace = true
adabt-opt.workspace = true
core_affinity = "0.8"
loom = { version = "0.7", optional = true }

[features]
loom = ["dep:loom", "adabt-storage/loom"]

[dev-dependencies]
adabt-testkit.workspace = true
tempfile = "3"
